apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 03-longhorn-rwo-4k-rr-single-sts
spec:
  serviceName: "longhorn-rwo-4k-rr-single"
  replicas: 1
  selector:
    matchLabels:
      app: 03-longhorn-rwo-4k-rr-single-sts
  template:
    metadata:
      labels:
        app: 03-longhorn-rwo-4k-rr-single-sts
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values: ["compute-node"]
      containers:
      - name: fio-test
        image: projectgreenist/fio-project:1.0
        command: ["/bin/sh", "-c"]
        args: ["fio --name=03-longhorn-rwo-4k-rr-single-sts --filename=/data/fiotest-${HOSTNAME}.tmp --rw=randread --bs=4k --ioengine=libaio --direct=1 --size=2G --numjobs=2 --iodepth=64 --runtime=60s --time_based --group_reporting && sleep infinity"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: fio-test-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: fio-test-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi 