apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 04-ceph-4k-rw-rwo-single-sts
spec:
  serviceName: "ceph-4k-rw-rwo-single"
  replicas: 1
  selector:
    matchLabels:
      app: 04-ceph-4k-rw-rwo-single-sts
  template:
    metadata:
      labels:
        app: 04-ceph-4k-rw-rwo-single-sts
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values: ["compute-node"]
      containers:
      - name: fio-test
        image: projectgreenist/fio-project:1.0
        command: ["fio"]
        args: [
          "--name=04-ceph-4k-rw-rwo-single-sts",
          "--filename=/data/fiotest-${HOSTNAME}.tmp",
          "--rw=randwrite",
          "--bs=4k",
          "--ioengine=libaio",
          "--direct=1",
          "--size=2G",
          "--numjobs=2",
          "--iodepth=64",
          "--runtime=60s",
          "--time_based",
          "--group_reporting"
        ]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: fio-test-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: fio-test-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-block
      resources:
        requests:
          storage: 10Gi 