apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 04-longhorn-rwo-4k-rw-multi-sts
spec:
  serviceName: "longhorn-4k-rw-rwo-multi"
  replicas: 3
  selector:
    matchLabels:
      app: 04-longhorn-rwo-4k-rw-multi-sts
  template:
    metadata:
      labels:
        app: 04-longhorn-rwo-4k-rw-multi-sts
    spec:
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values: ["compute-node"]
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: 04-longhorn-rwo-4k-rw-multi-sts
      containers:
      - name: fio-test
        image: projectgreenist/fio-project:1.0
        command: ["fio"]
        args: [
          "--name=04-longhorn-rwo-4k-rw-multi-sts",
          "--filename=/data/fiotest-${HOSTNAME}.tmp",
          "--rw=randwrite",
          "--bs=4k",
          "--ioengine=libaio",
          "--direct=1",
          "--size=2G",
          "--numjobs=2",
          "--iodepth=64",
          "--runtime=60s",
          "--time_based",
          "--group_reporting"
        ]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: fio-test-volume  
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: fio-test-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi 