---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-fs-rwx
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
